#
# Standard configuration
#
baseURL                = "easyformal.com"
copyright              = "The MIT License (MIT) Copyright © 2023 Jordan GAZEAU"
defaultContentLanguage = "zh"
enableEmoji            = false
enableGitInfo          = false
metaDataFormat         = "yaml"
publishDir             = "public"
title                  = "EasyFormal"
theme                  = "shadocs"
themesdir              = "themes"

[Author]
  name = "Zexun Luo"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.112.0'
    max = ''
  [[module.mounts]]
    source = 'asyncapi'
    target = 'static/asyncapi'
  [[module.mounts]]
    source = 'openapi'
    target = 'static/openapi'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 6
  [markup.goldmark.renderer]
    unsafe = false


[Languages]
  [Languages.zh]
    contentDir   = "content/zh"
    title        = "EasyFormal"
    weight       = 1
    languageName = "简体中文"

  [Languages.en]
    contentDir   = "content/en"
    title        = "EasyFormal"
    weight       = 2
    languageName = "English"

#
# Specific configuration
#
[params]
  logo                    = "images/logo.png"
  logoTouch               = "images/logoTouch.png"
  image404                = "images/404.gif"
  favicon                 = "images/favicon.png"
  faviconmd               = "![Favicon](/images/favicon.png)"
  homeLayout              = "onboarding"
  siteContentOrder        = "weight"
  toc                   = true
  # globalBanner          = true
  # currentVersion          = "latest"
  latestVersionUrl        = "https://shadocs.netlify.app/"
  # enforceRefrelLinks    = true


  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
    [params.taxonomies.tags]
      icon = "fa-solid fa-tag"
  [params.includes]
    jsModules = [
        "js/shortcuts.js"
      ]
    js        = []
    css       = [
        "css/shortcuts.css"
      ]
    sass      = [
        "sass/custom/example.sass"
    ]
  [params.versions]
    hugo_min         = "[0.112.0](https://github.com/gohugoio/hugo/releases/tag/v0.112.0)"
    bulma            = "[0.9.4](https://github.com/jgthms/bulma/releases/tag/0.9.4)"

[services]
  [services.googleAnalytics]
    ID = 'G-LR9116DJ4Y'